version: '3.2'

services:
  db:
    # build: .
    image: mssqldocker:v2017.CU12.1
    volumes:
      - mssql-server-data:/var/opt/mssql
    environment:
      - 'ACCEPT_EULA=Y'
      - 'SA_PASSWORD=Maverick782'
      - 'MSSQL_DB=pensiunku'
      - 'MSSQL_USER=root'
      - 'MSSQL_PASSWORD=Maverick782'
    ports:
      - "14330:1433"
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == pensiuncore

networks:
  default:
    external:
      name: appnet

volumes:
  mssql-server-data:

